# util/situacoes.py

situacoes = {
    1: "Pegou a peça e largou em algum lugar Aleatório",
    2: "Fez, sozinho, um agrupamento com 2 peças",
    3: "Fez, sozinho, um agrupamento com 3 a 6 peças",
    4: "Fez, sozinho, um agrupamento com mais de 6 peças",
    5: "Adicionou uma peça no agrupamento de outro integrante, fez várias vezes",
    8: "Colocou uma peça no tabuleiro de forma aleatória ou no próprio agrupamento e depois colocou a mesma peça no agrupamento do outro",
    10: "Adicionou uma peça no agrupamento do outro, que a remove, mas continua a repetir a ação",
    11: "Agrupou peças de cor igual",
    12: "Criou um agrupamento contendo peças iguais e diferentes. Exemplo: Duas amarelas e duas pretas",
    13: "Agrupou peças  de cores diferentes",
    14: "Retirou peças do Agrupamento do outro integrante e devolveu para o monte",
    15: "Retirou peças do Agrupamento do outro integrante  e colocou no seu próprio agrupamento",
    16: "Retirou peças do  Agrupamento do outro integrante  e colocou em um lugar aleatório",
    17: "Trocou a posição da própria peça",
    18: "Retirou peças do próprio Agrupamento e devolveu para o monte",
    19: "Retirou peças do próprio agrupamento e colocou em algum lugar aleatório",
    20: "Retirou peças dos outros integrantes que adicionaram no agrupamento feito por ele",
    21: "Criou mais de um agrupamento",
    22: "Conecta dois ou mais agrupamentos com outros participantes",
    23: "Conecta dois ou mais agrupamentos consigo mesmo",
    24: "Forma um agrupamento de 2 peças com outro integrante",
    25: "Forma um agrupamento de 3 a 6 peças com outro integrante",
    26: "Forma um agrupamento de mais de 6 peças com outro integrante",
    28: "Desistiu Sozinho",
    31: "Desistiu depois de outro integrante Desistir",
    32: "Finalizou sozinho",
    34: "Finalizou depois de outro integrante Finalizar",
    36: "Imitou a forma do mesmo agrupamento do outro (fez depois que outro integrante realizou a ação) ",
    38: "Não realizou ações",
}

operacoes = {
    1: ['Recebe informações externas (ORC), mas não organiza com os esquemas internos',
        'Autenticação constante pois esquemas não coincidem',
        'Inicia o processo, interage com o objeto epistêmico e o usa para um fim aleatório, pois ainda não tem compreensão',
        'Esquemas internos não coincidem com outros esquemas',
        'Reagrupa e articula esquemas internos, mas o processo é ineficaz',
        'Organiza esquemas internos, mas não obtém efetividade',
        'Entendimento é aleatório, e não consegue atribuir funções ao ORC',
        'Não entende o affordance do objeto epistêmico e pensa em um fim aleatório'],
    2: ['Organiza esquemas familiares com informações/esquemas externos',
        'Esquemas inovadores com funções e atribuições se tornam familiares e são colocados em contexto',
        'Organiza esquemas internos', 'Recebe informações externas (ORC) e organiza com os esquemas internos',
        'Esquemas internos são associados a informações externas',
        'Esquemas internos comparados com informações e esquemas externos',
        'Compara o que foi associado e atribuído com o contexto, mas não gera compreensão do objeto epistêmico. Aqui ocorre comparação com outras situações vividas anteriormente',
        'Inicia o processo, mas não tem plena compreensão do objeto epistêmico e passa a utilizá-lo por comparação de esquemas internos com esquemas e informações externas'],
    3: ['Organiza esquemas familiares com informações/esquemas externos',
        'Recebe informações externas (ORC) e organiza com os esquemas internos',
        'Esquemas internos são associados a informações externas',
        'Esquemas coincidem ao comparados (autenticação rápida). Assim as associações atribuições já foram realizadas anteriormente.',
        'Esquemas comparados coincidem, mas são colocados de forma diferente e geram novas demandas e funções',
        'Esquemas coincidem quando comparados, processo de autenticação rápido, haverá repetição',
        'Associa os esquemas internos com informações externas do ORC, atribuindo funções baseadas nos esquemas internos',
        'Compara o que foi associado e atribuído com o contexto, mas não entende as múltiplas funções do objeto epistêmico.'],
    4: ['Esquemas coincidem quando comparados, processo de autenticação rápido, haverá repetição',
        'Considera o contexto já vivido em situações semelhantes e aproveita as associações a atribuições obtidas anteriormente',
        'Entendimento criado através de esquemas que coincidem, ou seja, usados em situações semelhantes.',
        'Entendimento criado através dos esquemas internos',
        'Esquemas internos são autenticados e invalidam o contexto',
        'Compara o que foi associado e atribuído com o contexto, mas é seletivo e define somente informações que fazem parte dos esquemas internos',
        'Entendimento criado somente através dos esquemas internos',
        'Articula esquemas internos e considera os únicos possíveis para prover soluções ao problema'],
    5: ['Entendimento criado através dos esquemas externos. Os esquemas externos modificam os internos',
        'Entendimento criado através de esquemas que coincidem, ou seja, usados em situações semelhantes.',
        'Articula informações externas com esquemas internos', 'Percebe a interação através dos esquemas externos',
        'Organiza esquemas internos com informações/esquemas externos',
        'Esquemas externos são associados com esquemas internos e identifica outros affordances do objeto epistêmico. Passa a usar para diferentes fins',
        'Articula esquemas internos e externos para solucionar a situação-problema'],
    8: ['Articula fragmentos de esquemas familiares para assimilar ou acomodar',
        'Compara o que foi associado e atribuído com o contexto',
        'Associa esquemas internos com informações/esquemas externos',
        'Entendimento criado através da articulação entre informações externas (cenários e situações) e esquemas internos e externos.',
        'Usa o objeto epistêmico para um fim aleatório, percebe a ineficácia do affordance e dos esquemas utilizados, busca novos esquemas para atingir o mesmo fim de formas diferentes com objetos diferentes'],
    10: ['Recebe informações externas (ORC) e organiza com os esquemas internos',
         'Repete esquemas internos já existentes que que eventualmente foram eficazes na criação de soluções e associa com os elementos externos. Desenvolve centração e entende que as melhores soluções originam em si',
         'Entendimento criado somente através dos esquemas internos',
         'Articula esquemas internos e considera os únicos possíveis para prover soluções ao problema',
         'Esquemas não coincidem, novas situações emergem. Prioriza os esquemas internos pois entende que são os mais eficazes',
         'Articula esquemas internos para solucionar a situação-problema, obtém eficácia, desta forma usa o objeto epistêmico para um fim específico'],
    11: [
        'Limita o processo dando prioridade aos esquemas internos, define o affordance do objeto epistêmico e o usa para um fim específico',
        'Esquemas externos são associados com esquemas internos para que possa definir o affordance do objeto epistêmico e usar para um fim específico',
        'Esquemas comparados coincidem, define o affordance do objeto epistêmico e o usa para um fim específico',
        'Esquemas comparados coincidem, assim se limita a identificar os affordances do objeto epistêmico e passa usar para diferentes fins'],
    12: [
        'Esquemas externos são associados com esquemas internos para que possa definir o affordance do objeto epistêmico e usar para um fim específico',
        'Esquemas comparados não coincidem, utiliza o contexto para mobilizar novos esquemas',
        'Esquemas não coincidem, novas situações emergem. Prioriza os esquemas internos pois entende que são os mais eficazes',
        'Informações e esquemas externos não coincidem com outros esquemas',
        'Esquemas internos não coincidem com outros esquemas',
        'Compara o que foi associado e atribuído com o contexto, mas é seletivo e define somente informações que fazem parte dos esquemas internos'],
    13: [
        'Limita o processo dando prioridade aos esquemas internos, define o affordance do objeto epistêmico e o usa para um fim específico',
        'Esquemas externos são associados com esquemas internos para que possa definir o affordance do objeto epistêmico e usar para um fim específico',
        'Esquemas comparados não coincidem, busca novos esquemas para que possa definir o affordance do objeto epistêmico e usar para um fim específico',
        'Esquemas comparados não coincidem, busca novos esquemas e identifica outros affordances do objeto epistêmico. Passa a usar para diferentes fins'],
    14: ['Entendimento criado somente através dos esquemas internos',
         'Articula esquemas internos para solucionar a situação-problema. Define que a única forma de solucionar o problema e a sua',
         'Esquemas internos são associados a informações externas',
         'Informações externas são associados com esquemas internos'],
    15: ['Entendimento criado somente através dos esquemas internos',
         'Articula esquemas internos para solucionar a situação-problema. Define que a única forma de solucionar o problema e a sua',
         'Informações externas são associados com esquemas internos',
         'Articula esquemas internos e considera os únicos possíveis para prover soluções ao problema'],
    16: [
        'Articula esquemas internos para solucionar a situação-problema, não obtém eficácia, mesmo assim utiliza o objeto epistêmico para um fim aleatório. Repete a desequilibração cognitiva.',
        'Articula esquemas internos para solucionar a situação-problema, não obtém eficácia. Desta forma utiliza o objeto epistêmico para um fim aleatório',
        'Limita o processo dando prioridade aos esquemas internos, não define o affordance do objeto epistêmico e usa para um fim aleatório',
        'Esquemas comparados coincidem, mesmo assim não define o affordance do objeto epistêmico e usa para um fim aleatório'],
    17: ['Esquemas não coincidem ao comparados (autenticação continuada e recompensas parciais). Desagrupa componentes',
         'Desagrupa esquemas internos', 'Desagrupa componentes'],
    18: ['Esquemas não coincidem ao comparados (autenticação continuada e recompensas parciais). Desagrupa componentes',
         'Desagrupa esquemas internos', 'Desagrupa componentes',
         'Articula fragmentos de esquemas familiares para assimilar ou acomodar',
         'Não consegue associar ao contexto e transforma os esquemas familiares e as informações externas, em esquemas prototípicos (partículas de informação)'],
    19: ['Esquemas não coincidem ao comparados (autenticação continuada e recompensas parciais). Desagrupa componentes',
         'Desagrupa esquemas internos', 'Desagrupa componentes',
         'Não entende o affordance do objeto epistêmico e pensa em um fim aleatório',
         'Esquemas comparados não coincidem, assim não define o affordance do objeto epistêmico e usa para um fim aleatório'],
    20: [
        'Articula esquemas internos para solucionar a situação-problema, obtém eficácia, reagrupa esquemas prototípicos em inovadores e compreende diferentes fins para o objeto epistêmico',
        'Articula esquemas internos para solucionar a situação-problema, obtém eficácia, desta forma usa o objeto epistêmico para um fim específico',
        'Articula esquemas internos para solucionar a situação-problema, obtém eficácia, reagrupa esquemas prototípicos em inovadores e compreende como atingir o mesmo fim de formas diferentes com objetos epistêmicos diferentes',
        'Articula esquemas internos para solucionar a situação-problema. Define que a única forma de solucionar o problema e a sua',
        'Articula elementos externos aos esquemas internos, considera os esquemas internos o único meio possível para prover soluções'],
    21: ['Esquemas comparados não coincidem, utiliza o contexto para mobilizar novos esquemas',
         'Esquemas comparados não coincidem, busca novos esquemas para que possa definir o affordance do objeto epistêmico e usar para um fim específico',
         'Articula esquemas internos aos externos para antecipar ações já aprendidas e vividas. O processo gera novos esquemas'],
    22: [
        'Percebe que a interação pode alterar seus esquemas internos através dos esquemas externos, assim permite que isso aconteça',
        'Esquemas não coincidem, esquemas externos e internos são articulados novas soluções emergem',
        'Entendimento criado através de esquemas que não coincidem, ou seja, não foram usados em situações semelhantes.',
        'Esquemas comparados não coincidem, busca novos esquemas e identifica outros affordances do objeto epistêmico. Passa a usar para diferentes fins',
        'Articula esquemas internos aos externos para antecipar ações já aprendidas e vividas. O processo gera novos esquemas'],
    23: ['Esquemas internos coincidem com outros esquemas',
         'Esquemas coincidem quando comparados, processo de autenticação rápido, haverá repetição',
         'Reagrupa componentes e identifica os affordances (autenticação rápida)',
         'Articula esquemas internos e considera os únicos possíveis para prover soluções ao problema'],
    24: ['Informações e esquemas externos não coincidem com outros esquemas',
         'Esquemas não coincidem, esquemas externos e internos são articulados novas soluções emergem',
         'Percebe a interação através dos esquemas externos',
         'Reagrupa e articula esquemas internos e externos. Não prioriza componentes, assim promove a integração dos esquemas',
         'Unifica os esquemas prototípicos (externos e internos) e informações externas para associar e atribui função de acordo com o contexto. Constrói assim um esquema inovador, com funções e atribuições atreladas ao contexto'],
    25: ['Esquemas comparados coincidem, define o affordance do objeto epistêmico e o usa para um fim específico',
         'Esquemas internos coincidem, mas percebe que precisa articular com esquemas externos. Permite que os esquemas externos modifiquem os esquemas internos',
         'Articula os múltiplos componentes e cria estratégias operatórias para escolher os mais eficazes na solução da situação-problema, obtém eficácia, desta forma usa o objeto epistêmico para um fim específico'],
    26: ['Define quais das diferentes soluções para o mesmo fim com objetos epistêmicos diferentes serão usadas',
         'Esquemas comparados coincidem, assim define contexto e affordances dos objetos epistêmicos e os diversos meios de chegar aos mesmos fins. O processo ocorre de acordo com a sua centração.',
         'Esquemas comparados coincidem, define o affordance do objeto epistêmico e o usa para um fim específico',
         'Esquemas internos coincidem, mas percebe que precisa articular com esquemas externos. Permite que os esquemas externos modifiquem os esquemas internos',
         'Articula os múltiplos componentes e cria estratégias operatórias para escolher os mais eficazes na solução da situação-problema, obtém eficácia, desta forma usa o objeto epistêmico para um fim específico'],
    28: [
        'Articula somente esquemas internos para solucionar a situação-problema, mas age como autodefesa e entra em evitação',
        'Autentica os esquemas de forma rápida e simplificada, necessidades primárias. Desenvolve autodefesa e evita a situação-problema',
        'Reagrupa e articula esquemas internos, mas o processo é ineficaz assim passa a evitar a situação-problema',
        'Não identifica o problema, sendo assim não entende quais esquemas podem ser utilizados. Prioriza esquemas internos',
        'Não identifica um problema para ser resolvido'],
    31: [
        'Para autodefesa e manutenção das associações e articulações já desenvolvidas, aceita esquemas externos pois os esquemas internos são ineficazes',
        'Esquemas não coincidem, novas soluções emergem. Percebe insuficiência nas soluções que emergiram e opta por aceitar ou copiar elementos externos',
        'Articula esquemas internos e externos por achar que o uso de somente esquemas internos não terá eficácia, assim evita entrar em conflito e aceita o que o outro determina'],
    32: [
        'Articula somente esquemas internos para solucionar a situação-problema, mas age como autodefesa e entra em evitação',
        'Compara esquemas internos ao contexto',
        'Entendimento criado através de esquemas internos e externos. Por conta da autodefesa, prioriza os esquemas internos para haver alguma manutenção deles no processo de interação'],
    34: [
        'Entendimento criado através de esquemas internos e externos. Prioriza os esquemas externos, considera ineficaz os esquemas internos e aceita o que o outro determina',
        'Esquemas não coincidem, novas soluções emergem. Percebe insuficiência nas soluções que emergiram e opta por aceitar ou copiar elementos externos',
        'Autentica os esquemas de forma rápida e simplificada, necessidades primárias. Desenvolve autodefesa, aceita ou copia os esquemas externos por conta da falta de esquemas internos eficazes.'],
    36: [
        'Para autodefesa e manutenção das associações e articulações já desenvolvidas, aceita esquemas externos pois eles coincidem com os esquemas internos',
        'Reagrupa e articula esquemas internos e externos, mas tem como prioridade uso os esquemas externos por considerar os internos ineficazes. Utiliza o objeto epistêmico para um fim específico',
        'Entendimento criado através de esquemas internos e externos. Prioriza os esquemas externos, considera ineficaz os esquemas internos e aceita o que o outro determina',
        'Reagrupa e articula esquemas internos e externos por achar que o uso de somente esquemas internos não terá eficácia, assim evita entrar em conflito e aceita o que o outro determina',
        'Esquemas não coincidem, novas soluções emergem. Percebe insuficiência nas soluções que emergiram e opta por aceitar ou copiar elementos externos',
        'Articula esquemas internos e externos por achar que o uso de somente esquemas internos não terá eficácia, assim evita entrar em conflito e aceita o que o outro determina'],
    38: [
        'Articula somente esquemas internos para solucionar a situação-problema, mas age como autodefesa e entra em evitação',
        'Não identifica um problema para ser resolvido, assim age como autodefesa e entra em evitação',
        'Entendimento criado é ineficiente, assim age como autodefesa e entra em evitação'],
}

perguntas = {
    0: [
        'Você ajusta suas jogadas com base na suposição de que outros jogadores podem pensar de forma semelhante a você?',
        'Você considera algum aspecto do jogo particularmente desafiador?',
        'Você planeja suas jogadas antes de começar a posicionar as peças?'],
    1: ['Havia algo que impediu você de interagir com os outros jogadores?',
        'Você avalia se uma jogada foi bem-sucedida após concluí-la?'],
    2: ['Você está seguindo regras específicas no jogo?', 'Você definiu um objetivo principal ao jogar este jogo?'],
    3: ['Você acredita que existe uma maneira correta de todos jogarem',
        'Você definiu indicadores de desempenho específicos para acompanhar seu progresso no jogo?',
        'Você definiu indicadores de desempenho específicos para acompanhar seu progresso no jogo?'],
    4: ['Você acredita que a forma como organiza suas peças reflete as regras universais do jogo/instrumento?'],
    5: ['Você interagiu com os outros jogadores?',
        'Você acredita que todos os jogadores interpretam a dinâmica do jogo da mesma maneira?',
        'Você relaciona as ações dos outros jogadores com as suas para melhorar sua estratégia?',
        'Você tem critérios específicos para determinar se atingiu seu objetivo no jogo?'],
    8: ['Você acredita que suas escolhas no jogo são mais eficazes do que as dos outros jogadores?'],
    11: ['Você escolheu formar um agrupamento com peças iguais?'],
    12: ['Você adapta sua estratégia com base no que observa nos outros jogadores?'],
    13: ['Você escolheu formar um agrupamento com peças diferentes?',
         'Seu objetivo principal guia suas decisões durante a partida?'],
    14: ['O sucesso ou falha de outros jogadores influencia a forma como você posiciona suas peças?',
         'Você retirou uma peça do lugar que o outro jogador havia colocado?'],
    15: ['Você prioriza algum objetivo específico ao interagir com outros jogadores?'],
    17: ['A forma como os outros jogadores organizam suas peças influencia suas decisões?',
         'Você acha que a estratégia de outro jogador já foi melhor ou pior do que a sua?',
         'Você retirou uma peça que você mesmo havia colocado?',
         'Há indicadores específicos que fazem você mudar sua estratégia?',
         'Quando você sente que uma tarefa é fácil ou difícil, isso afeta suas próximas jogadas?',
         'Você altera sua estratégia ao sentir frustração ou satisfação durante o jogo?',
         'Quando uma jogada não tem o efeito esperado, você muda sua abordagem no jogo?'],
    18: ['Você corrige suas ações quando percebe que está prestes a cometer um erro ao posicionar as peças?',
         'Você alterou seus objetivos ao longo do jogo com base na evolução da partida?'],
    19: ['Você analisa as razões de uma jogada que não sai como o esperado?'],
    20: ['Algo específico fez você decidir interagir com os outros jogadores?'],
    21: ['Você acredita que existe uma maneira específica de agir nesse jogo/instrumento?',
         'Você acha que algumas ações no jogo requerem mais planejamento do que outras?',
         'Você utiliza estratégias específicas para posicionar as peças e alcançar seus objetivos?',
         'Você decide previamente qual estratégia vai usar para formar um agrupamento?'],
    24: ['Você percebe diferenças entre a sua forma de jogar e a dos outros jogadores?'],
    25: ['Você acredita que todos os jogadores seguem padrões similares de pensamento?'],
    28: ['Você decidiu desistir do jogo?'],
    32: ['Havia algo que fez você finalizar o jogo?', 'Você decidiu finalizar o jogo?'],
    36: ['Você verifica se está utilizando a melhor estratégia durante o jogo?'],
    38: ['Você planeja suas jogadas antes de executá-las?'],
}

perguntas_unica = {
    1: "Havia algo que impediu você de interagir com os outros jogadores?",
    2: "Você planeja suas jogadas antes de executá-las?",
    3: "Você está seguindo regras específicas no jogo?",
    4: "Você acredita que existe uma maneira correta de todos jogarem?",
    5: "Você definiu indicadores de desempenho específicos para acompanhar seu progresso no jogo?",
    6: "Você acredita que a forma como organiza suas peças reflete as regras universais do jogo/instrumento?",
    7: "Você interagiu com os outros jogadores?",
    8: "Você acredita que todos os jogadores interpretam a dinâmica do jogo da mesma maneira?",
    9: "Você relaciona as ações dos outros jogadores com as suas para melhorar sua estratégia?",
    10: "Você tem critérios específicos para determinar se atingiu seu objetivo no jogo?",
    11: "Você acredita que suas escolhas no jogo são mais eficazes do que as dos outros jogadores?",
    12: "Você escolheu formar um agrupamento com peças iguais?",
    13: "Você utiliza estratégias específicas para posicionar as peças e alcançar seus objetivos?",
    14: "Você adapta sua estratégia com base no que observa nos outros jogadores?",
    15: "Você escolheu formar um agrupamento com peças diferentes?",
    16: "Seu objetivo principal guia suas decisões durante a partida?",
    17: "O sucesso ou falha de outros jogadores influencia a forma como você posiciona suas peças?",
    18: "Você prioriza algum objetivo específico ao interagir com outros jogadores?",
    19: "A forma como os outros jogadores organizam suas peças influencia suas decisões?",
    20: "Você acha que a estratégia de outro jogador já foi melhor ou pior do que a sua?",
    21: "Você acredita que há indicadores específicos que fazem você mudar sua estratégia?",
    22: "Você altera sua estratégia ao sentir frustração ou satisfação durante o jogo?",
    23: "Quando você sente que uma tarefa é fácil ou difícil, isso afeta suas próximas jogadas?",
    24: "Quando uma jogada não tem o efeito esperado, você muda sua abordagem no jogo?",
    25: "Você corrige suas ações quando percebe que está prestes a cometer um erro ao posicionar as peças?",
    26: "Você alterou seus objetivos ao longo do jogo com base na evolução da partida?",
    27: "Você analisa as razões de uma jogada que não sai como o esperado?",
    28: "Há indicadores específicos que fazem você mudar sua estratégia?",
    29: "Algo específico fez você decidir interagir com os outros jogadores?",
    30: "Você acredita que existe uma maneira específica de agir nesse jogo/instrumento?",
    31: "Você acha que algumas ações no jogo requerem mais planejamento do que outras?",
    32: "Você decide previamente qual estratégia vai usar para formar um agrupamento?",
    33: "Você percebe diferenças entre a sua forma de jogar e a dos outros jogadores?",
    34: "Você acredita que todos os jogadores seguem padrões similares de pensamento?",
    35: "Você ajusta suas jogadas com base na suposição de que outros jogadores podem pensar de forma semelhante a você?",
    36: "Você decidiu desistir do jogo?",
    37: "Você altera sua estratégia ao sentir frustração ou satisfação durante o jogo?",
    38: "Algo específico fez você finalizar o jogo?",
    39: "Você decidiu finalizar o jogo?",
    40: "Havia algo que fez você finalizar o jogo?",
    41: "Você verifica se está utilizando a melhor estratégia durante o jogo?"
}

estado1 = {
    1: ['Percepção das informações obtidas', 'Inovação ou Objeto Novo', 'Objeto Real do Conhecimento',
        'Ponto de Vista Interno', 'Une esquemas para solucionar um problema',
        'Articula informações do resultado do processo de assimilação e acomodação.', 'Estruturação Lógica',
        'Estruturação Lógica'],
    2: ['Articula informações do resultado do processo de assimilação e acomodação.',
        'Articula informações do resultado do processo de assimilação e acomodação.',
        'Articula informações do resultado do processo de assimilação e acomodação.',
        'Percepção das informações obtidas', 'Designação e Atribuição através das associações',
        'Ponto de Vista externo', 'Contexto e criação de Imaginário ', 'Objeto Real do Conhecimento'],
    3: ['Articula informações do resultado do processo de assimilação e acomodação.',
        'Percepção das informações obtidas', 'Designação e Atribuição através das associações',
        'Designação e Atribuição através das associações', 'Inovação ou Objeto Novo',
        'Recompensa por Processos biológicos', 'Designação e Atribuição através das associações',
        'Contexto e criação de Imaginário '],
    4: ['Recompensa por Processos biológicos', 'Contexto e criação de Imaginário ', 'Estruturação Lógica',
        'Estruturação Lógica', 'Contexto e criação de Imaginário ', 'Contexto e criação de Imaginário ',
        'Estruturação Lógica', 'Ponto de Vista interno'],
    5: ['Estruturação Lógica', 'Estruturação Lógica', 'Ponto de Vista externo', 'Ponto de Vista externo',
        'Articula informações do resultado do processo de assimilação e acomodação.', 'Ponto de Vista externo',
        'Identidade Autêntica de Compromisso'],
    8: ['Articula informações do resultado do processo de assimilação e acomodação.',
        'Contexto e criação de Imaginário', 'Designação e Atribuição através das associações', 'Estruturação Lógica',
        'Prototipagem'],
    10: ['Percepção das informações obtidas', 'Iteração/Repetição ou Objeto Iterado dotado de significado',
         'Estruturação Lógica', 'Ponto de Vista interno', 'Inovação ou Objeto Novo', 'Pertença Infantil Egocêntrica'],
    11: ['Ponto de Vista interno', 'Ponto de Vista externo',
         'Iteração/Repetição ou Objeto Iterado dotado de significado',
         'Iteração/Repetição ou Objeto Iterado dotado de significado'],
    12: ['Ponto de Vista externo', 'Inovação ou Objeto Novo', 'Inovação ou Objeto Novo', 'Ponto de Vista externo',
         'Ponto de Vista Interno', 'Contexto e criação de Imaginário '],
    13: ['Ponto de Vista interno', 'Ponto de Vista externo', 'Inovação ou Objeto Novo', 'Inovação ou Objeto Novo'],
    14: ['Estruturação Lógica', 'Pertença Infantil Egocêntrica', 'Designação e Atribuição através das associações',
         'Designação e Atribuição através das associações'],
    15: ['Estruturação Lógica', 'Pertença Infantil Egocêntrica', 'Designação e Atribuição através das associações',
         'Ponto de Vista interno'],
    16: ['Identidade Autêntica de Dominação', 'Pertença Infantil Passiva', 'Ponto de Vista interno',
         'Iteração/Repetição ou Objeto Iterado dotado de significado'],
    17: ['Desagrupa os componentes dos esquemas familiares', 'Desagrupa os componentes dos esquemas familiares',
         'Desagrupa os componentes dos esquemas familiares'],
    18: ['Desagrupa os componentes dos esquemas familiares', 'Desagrupa os componentes dos esquemas familiares',
         'Desagrupa os componentes dos esquemas familiares',
         'Articula informações do resultado do processo de assimilação e acomodação.',
         'Desagrupa os componentes dos esquemas familiares'],
    19: ['Desagrupa os componentes dos esquemas familiares', 'Desagrupa os componentes dos esquemas familiares',
         'Desagrupa os componentes dos esquemas familiares', 'Estruturação Lógica', 'Inovação ou Objeto Novo'],
    20: ['Pertença Infantil Egocêntrica', 'Pertença Infantil Egocêntrica', 'Pertença Infantil Egocêntrica',
         'Pertença Infantil Egocêntrica', 'Ponto de Vista externo'],
    21: ['Inovação ou Objeto Novo', 'Inovação ou Objeto Novo', 'Estruturação Lógica'],
    22: ['Ponto de Vista interno', 'Inovação ou Objeto Novo', 'Estruturação Lógica', 'Inovação ou Objeto Novo',
         'Estruturação Lógica'],
    23: ['Ponto de Vista interno', 'Recompensa por Processos biológicos', 'Une esquemas para solucionar um problema',
         'Ponto de Vista interno'],
    24: ['Ponto de Vista externo', 'Inovação ou Objeto Novo', 'Ponto de Vista externo',
         'Une esquemas para solucionar um problema', 'Une esquemas para solucionar um problema'],
    25: ['Iteração/Repetição ou Objeto Iterado dotado de significado',
         'Iteração/Repetição ou Objeto Iterado dotado de significado', 'Pertença Adolescente Personalizada'],
    26: ['Estruturação Lógica', 'Iteração/Repetição ou Objeto Iterado dotado de significado',
         'Iteração/Repetição ou Objeto Iterado dotado de significado',
         'Iteração/Repetição ou Objeto Iterado dotado de significado', 'Pertença Adolescente Personalizada'],
    28: ['Pertença Infantil Egocêntrica', 'Recompensa por Processos biológicos',
         'Une esquemas para solucionar um problema',
         'Articula informações do resultado do processo de assimilação e acomodação.', 'Pertença Infantil Egocêntrica'],
    31: ['Pertença Infantil Passiva', 'Inovação ou Objeto Novo', 'Identidade Autêntica de Evitação'],
    32: ['Pertença Infantil Egocêntrica', 'Pertença Infantil Egocêntrica', 'Estruturação Lógica'],
    34: ['Estruturação Lógica', 'Inovação ou Objeto Novo', 'Recompensa por Processos biológicos'],
    36: ['Pertença Infantil Egocêntrica', 'Inferência', 'Estruturação Lógica',
         'Une esquemas para solucionar um problema', 'Inovação ou Objeto Novo', 'Identidade Autêntica de Evitação'],
    38: ['Pertença Infantil Egocêntrica', 'Pertença Infantil Passiva', 'Estruturação Lógica'],
}

estado2 = {
    1: ['Pertença Infantil Difusa', 'Recompensa por processos de desenvolvimento', 'Prototipagem',
        'Inovação Ou Objeto Novo', 'Pertença Infantil Passiva', 'Pertença Infantil Passiva',
        'Objeto Real do Conhecimento', 'Prototipagem'],
    2: ['Percepção das informações obtidas', 'Contexto e criação de Imaginário ', 'Ponto de Vista interno',
        'Ponto de Vista interno', 'Ponto de Vista interno', 'Ponto de Vista interno', 'Paradoxo', 'Paradoxo'],
    3: ['Percepção das informações obtidas', 'Ponto de Vista interno', 'Ponto de Vista interno',
        'Iteração/Repetição ou Objeto Iterado dotado de significado',
        'Iteração/Repetição ou Objeto Iterado dotado de significado',
        'Iteração/Repetição ou Objeto Iterado dotado de significado', 'Pertença Infantil Egocêntrica', 'Inferência'],
    4: ['Iteração/Repetição ou Objeto Iterado dotado de significado',
        'Iteração/Repetição ou Objeto Iterado dotado de significado',
        'Iteração/Repetição ou Objeto Iterado dotado de significado', 'Ponto de Vista interno',
        'Ponto de Vista interno', 'Pertença Infantil Egocêntrica', 'Pertença Infantil Egocêntrica',
        'Pertença Infantil Egocêntrica'],
    5: ['Ponto de Vista externo', 'Iteração/Repetição ou Objeto Iterado dotado de significado',
        'Pertença Adolescente Descentrada', 'Identidade Autêntica de Compromisso',
        'Iteração/Repetição ou Objeto Iterado dotado de significado', 'Inovação', 'Identidade Autêntica de Integração'],
    8: ['Desagrupa os componentes dos esquemas familiares', 'Identidade Autêntica de Compromisso',
        'Identidade Autêntica de Compromisso', 'Identidade Autêntica de Integração', 'Expansão Pioneira'],
    10: ['Ponto de Vista interno', 'Pertença Infantil Egocêntrica', 'Pertença Infantil Egocêntrica',
         'Pertença Infantil Egocêntrica', 'Pertença Infantil Egocêntrica', 'Inferência'],
    11: ['Inferência', 'Inferência', 'Inferência', 'Inovação'],
    12: ['Inferência', 'Pertença Adolescente Descentrada', 'Pertença Infantil Egocêntrica', 'Inovação ou Objeto Novo',
         'Inovação Ou Objeto Novo', 'Pertença Infantil Egocêntrica'],
    13: ['Inferência', 'Inferência', 'Inferência', 'Inovação'],
    14: ['Pertença Infantil Egocêntrica', 'Identidade Autêntica de Dominação', 'Ponto de Vista interno',
         'Ponto de Vista externo'],
    15: ['Pertença Infantil Egocêntrica', 'Identidade Autêntica de Dominação', 'Ponto de Vista externo',
         'Pertença Infantil Egocêntrica'],
    16: ['Prototipagem', 'Prototipagem', 'Prototipagem', 'Prototipagem'],
    17: ['Inovação ou Objeto Novo', 'Ponto de Vista interno', 'Objeto Real do Conhecimento'],
    18: ['Inovação ou Objeto Novo', 'Ponto de Vista interno', 'Objeto Real do Conhecimento',
         'Desagrupa os componentes dos esquemas familiares', 'Contexto e criação de Imaginário '],
    19: ['Inovação ou Objeto Novo', 'Ponto de Vista interno', 'Objeto Real do Conhecimento', 'Prototipagem',
         'Prototipagem'],
    20: ['Inovação', 'Inferência', 'Expansão Pioneira', 'Identidade Autêntica de Dominação',
         'Pertença Infantil Egocêntrica'],
    21: ['Pertença Adolescente Descentrada', 'Inferência', 'Conteúdo Processo'],
    22: ['Identidade Autêntica de Integração', 'Identidade Autêntica de Integração', 'Inovação ou Objeto Novo',
         'Inovação', 'Conteúdo Processo'],
    23: ['Iteração/Repetição ou Objeto Iterado dotado de significado',
         'Iteração/Repetição ou Objeto Iterado dotado de significado',
         'Iteração/Repetição ou Objeto Iterado dotado de significado', 'Pertença Infantil Egocêntrica'],
    24: ['Inovação ou Objeto Novo', 'Identidade Autêntica de Integração', 'Identidade Autêntica de Compromisso',
         'Identidade Autêntica de Integração', 'Contexto e criação de Imaginário '],
    25: ['Inferência', 'Identidade Autêntica de Integração', 'Inferência'],
    26: ['Expansão Pioneira', 'Expansão Pioneira', 'Inferência', 'Identidade Autêntica de Integração', 'Inferência'],
    28: ['Identidade Autêntica de Evitação', 'Identidade Autêntica de Evitação', 'Identidade Autêntica de Evitação',
         'Pertença Infantil Difusa', 'Pertença Infantil Difusa'],
    31: ['Identidade Autêntica de Aceitação', 'Pertença Infantil Passiva', 'Identidade Autêntica de Aceitação'],
    32: ['Identidade Autêntica de Evitação', 'Pertença Adolescente Descentrada', 'Identidade Autêntica de Compromisso'],
    34: ['Identidade Autêntica de Aceitação', 'Pertença Infantil Passiva', 'Identidade Autêntica de Aceitação'],
    36: ['Identidade Autêntica de Aceitação', 'Identidade Autêntica de Aceitação', 'Identidade Autêntica de Aceitação',
         'Identidade Autêntica de Aceitação', 'Pertença Infantil Passiva', 'Identidade Autêntica de Aceitação'],
    38: ['Identidade Autêntica de Evitação', 'Identidade Autêntica de Evitação', 'Pertença Infantil Passiva'],
}
