# util/situacoes.py

situacoes = {
    1: "Pegou a peça e largou em algum lugar Aleatório",
    2: "Fez, sozinho, um agrupamento com 2 peças",
    3: "Fez, sozinho, um agrupamento com 3 a 6 peças",
    4: "Fez, sozinho, um agrupamento com mais de 6 peças",
    5: "Adicionou uma peça no agrupamento de outro integrante, fez várias vezes",
    6: "Adicionou uma peça no agrupamento de outro integrante, faz somente uma vez num período curto",
    7: "Segurou uma peça por mais de 6 segundos por exemplo",
    8: "Colocou uma peça no tabuleiro de forma aleatória ou no próprio agrupamento e depois colocou a mesma peça no agrupamento do outro",
    9: "Realizou uma ação rápida, menos de 3 segundos",
    10: "Adicionou uma peça no agrupamento do outro, que a remove, mas continua a repetir a ação",
    11: "Agrupou peças de cor igual",
    12: "Criou um agrupamento contendo peças iguais e diferentes. Exemplo: Duas amarelas e duas pretas",
    13: "Agrupou peças de cores diferentes",
    14: "Retirou peças do Agrupamento do outro integrante e devolveu para o monte",
    15: "Retirou peças do Agrupamento do outro integrante e colocou no seu próprio agrupamento",
    16: "Retirou peças do Agrupamento do outro integrante e colocou em um lugar aleatório",
    17: "Trocou a posição da própria peça",
    18: "Retirou peças do próprio Agrupamento e devolveu para o monte",
    19: "Retirou peças do próprio agrupamento e colocou em algum lugar aleatório",
    20: "Retirou peças dos outros integrantes que adicionaram no agrupamento feito por ele",
    21: "Criou mais de um agrupamento",
    22: "Conecta dois ou mais agrupamentos com outros participantes",
    23: "Conecta dois ou mais agrupamentos consigo mesmo",
    24: "Forma um agrupamento de 2 peças com outro integrante",
    25: "Forma um agrupamento de 3 a 6 peças com outro integrante",
    26: "Forma um agrupamento de mais de 6 peças com outro integrante",
    27: "Desenvolveu um agrupamento e outro integrante resolveu adicionar peças",
    28: "Desistiu Sozinho",
    29: "Desistiu Sozinho com pouco tempo de jogo",
    30: "Desistiu Sozinho e pouco tempo depois outro integrante desistiu",
    31: "Desistiu depois de outro integrante Desistir",
    32: "Finalizou sozinho",
    33: "Finalizou sozinho com pouco tempo de jogo",
    34: "Finalizou depois de outro integrante Finalizar",
    35: "Finalizou Sozinho e pouco tempo depois outro integrante finalizou também",
    36: "Imitou a forma do mesmo agrupamento do outro (fez depois que outro integrante realizou a ação)",
    37: "É imitado por alguém",
    38: "Não realizou ações"
}

acoes_genericas = {
    1: ["Executa Tarefas Simples", "Não se Envolve / Evita Envolvimento", "Ignora Contribuições Alheias", "Evita Participar", "Desconsidera o Grupo", "Contribui Esporadicamente", "Desmotiva o Grupo"],
    2: ["Não se Envolve", "Monitora e Avalia Progresso"],
    3: ["Planeja Estratégicamente", "Centraliza Decisões", "Define Visão de Longo Prazo", "Define Metas Claras", "Monitora e Avalia Progresso", "Não se Envolve"],
    4: ["Planeja Estratégicamente", "Desconsidera o Grupo", "Centraliza Decisões", "Define Visão de Longo Prazo", "Define Metas Claras", "Ignora Conflitos", "Ignora Contribuições Alheias", "Prioriza Interesses Próprios", "Não se Envolve"],
    5: ["Planeja Estratégicamente", "Define Visão de Longo Prazo", "Contribui com Ideias", "Participa das Decisões"],
    6: ["Contribui Esporadicamente", "Participa Quando Interessado", "Planeja Estratégicamente", "Monitora e Avalia Progresso", "Prioriza Interesses Próprios"],
    7: ["Executa Tarefas Simples", "Planeja Estratégicamente", "Centraliza Decisões"],
    8: ["Participa Quando Interessado", "Contribui com Ideias"],
    9: ["Define Metas Claras", "Executa Tarefas Simples"],
    10: ["Cria Conflitos", "Contribui com Ideias", "Centraliza Decisões", "Desorganiza o Trabalho", "Prioriza Interesses Próprios"],
    11: ["Planeja Estratégicamente", "Define Visão de Longo Prazo", "Define Metas Claras", "Monitora e Avalia Progresso"],
    12: ["Planeja Estratégicamente", "Define Visão de Longo Prazo", "Desempenha Funções Variadas", "Monitora e Avalia Progresso", "Define Metas Claras"],
    13: ["Planeja Estratégicamente", "Desempenha Funções Variadas", "Define Visão de Longo Prazo", "Define Metas Claras", "Monitora e Avalia Progresso"],
    14: ["Desconsidera o Grupo", "Desmotiva o Grupo", "Cria Conflitos", "Centraliza Decisões", "Desorganiza o Trabalho", "Ignora Contribuições Alheias"],
    15: ["Desconsidera o Grupo", "Cria Conflitos", "Centraliza Decisões", "Prioriza Interesses Próprios", "Ignora Contribuições Alheias", "Desorganiza o Trabalho", "Planeja Estratégicamente"],
    16: ["Desconsidera o Grupo", "Desmotiva o Grupo", "Cria Conflitos", "Centraliza Decisões", "Desorganiza o Trabalho", "Ignora Contribuições Alheias"],
    17: ["Centraliza Decisões", "Planeja Estratégicamente", "Define Visão de Longo Prazo", "Executa Tarefas Simples", "Ignora Conflitos", "Monitora e Avalia Progresso"],
    18: ["Centraliza Decisões", "Define Visão de Longo Prazo", "Monitora e Avalia Progresso"],
    19: ["Centraliza Decisões", "Desmotiva o Grupo", "Define Visão de Longo Prazo", "Desorganiza o Trabalho", "Monitora e Avalia Progresso"],
    20: ["Desmotiva o Grupo", "Desconsidera o Grupo", "Ignora Contribuições Alheias", "Cria Conflitos", "Monitora e Avalia Progresso", "Prioriza Interesses Próprios", "Centraliza Decisões", "Define Visão de Longo Prazo"],
    21: ["Desempenha Funções Variadas", "Centraliza Decisões", "Planeja Estratégicamente", "Monitora e Avalia Progresso", "Define Visão de Longo Prazo"],
    22: ["Planeja Estratégicamente", "Desempenha Funções Variadas", "Monitora e Avalia Progresso", "Segue Instruções", "Contribui com Ideias", "Define Visão de Longo Prazo"],
    23: ["Planeja Estratégicamente", "Centraliza Decisões", "Desempenha Funções Variadas", "Monitora e Avalia Progresso", "Ignora Conflitos", "Define Visão de Longo Prazo"],
    24: ["Contribui com Ideias", "Monitora e Avalia Progresso"],
    25: ["Define Visão de Longo Prazo", "Contribui com Ideias", "Monitora e Avalia Progresso"],
    26: ["Define Visão de Longo Prazo", "Contribui com Ideias", "Segue Instruções", "Participa das Decisões", "Age de forma reciproca", "Monitora e Avalia Progresso"],
    27: ["Conduz as Decisões do Grupo"],
    28: ["Evita Participar", "Ignora Conflitos", "Centraliza Decisões", "Monitora e Avalia Progresso", "Prioriza Interesses Próprios", "Ignora Contribuições Alheias", "Desmotiva o Grupo"],
    29: ["Evita Participar", "Ignora Conflitos", "Monitora e Avalia Progresso"],
    30: ["Conduz as Decisões do Grupo"],
    31: ["Copia o Outro", "Desmotiva o Grupo", "Monitora e Avalia Progresso"],
    32: ["Desconsidera o Grupo", "Centraliza Decisões", "Prioriza Interesses Próprios", "Monitora e Avalia Progresso", "Desmotiva o Grupo"],
    33: ["Monitora e Avalia Progresso", "Centraliza Decisões", "Prioriza Interesses Próprios"],
    34: ["Copia o Outro", "Monitora e Avalia Progresso"],
    35: ["Conduz as Decisões do Grupo", "Participa das Decisões"],
    36: ["Copia o Outro", "Ignora Conflitos", "Monitora e Avalia Progresso"],
    37: ["Conduz as Decisões do Grupo", "Participa das Decisões"],
    38: ["Evita Participar", "Não se Envolve", "Ignora Contribuições Alheias"]
}
